include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
  errors:
    invalid_annotation_target: ignore
    public_member_api_docs: ignore # Unnecessary for mostly private apps unless building packages
    lines_longer_than_80_chars: ignore # A bit too restrictive for Flutter apps
    sort_pub_dependencies: ignore

linter:
  rules:
    sort_constructors_first: true
    prefer_single_quotes: true
    always_declare_return_types: true
    depend_on_referenced_packages: false # Often bugs out with mono repo or certain generators
