// Mocks generated by Mockito 5.4.6 from annotations
// in weathernav/test/data/repositories/offline_zones_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:weathernav/domain/repositories/settings_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i2.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  T? get<T>(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as T?);

  @override
  T getOrDefault<T>(String? key, T? defaultValue) =>
      (super.noSuchMethod(
            Invocation.method(#getOrDefault, [key, defaultValue]),
            returnValue: _i3.dummyValue<T>(
              this,
              Invocation.method(#getOrDefault, [key, defaultValue]),
            ),
          )
          as T);

  @override
  _i4.Future<void> put(String? key, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#put, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> delete(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<void> watch(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [key]),
            returnValue: _i4.Stream<void>.empty(),
          )
          as _i4.Stream<void>);
}
